# -*- coding: utf-8 -*-
"""CIFAR10-cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ux0EagbjxxWFm6Ny6h26yaQumSCuFacc
"""

import tensorflow as tf
from tensorflow.keras import datasets,layers,models
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix
import seaborn as sns
import numpy as np



"""load cifar-10 dataset

"""

from tensorflow.keras import datasets
(x_train,y_train),(x_test,y_test)=datasets.cifar10.load_data()

x_train.shape

y_train.shape

x_test.shape

y_test.shape

"""shape of a single image"""

print("shape of a single image(x_train[0]:",x_train[0].shape)



"""normalization"""

x_train,x_test=x_train/225.0,x_test/225.0



"""flatten labels"""

y_train=y_train.flatten()
y_test=y_test.flatten()

class_names=['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']



"""plot a sample image"""

def plot_sample(x,y,index):
  plt.figure(figsize=(3,3))
  plt.imshow(x[index])
  plt.xlabel(class_names[y[index]])
  plt.title("sample training image")
  plt.show()
plot_sample(x_train,y_train,45000)



"""build the layer"""

model=models.Sequential([
    layers.Conv2D(32,(3,3),activation="relu",input_shape=(32,32,3)),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64,(3,3),activation="relu"),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64,(3,3),activation="relu"),
    layers.Flatten(),
    layers.Dense(64,activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(10,activation="softmax")
    ])

"""model compiler"""

model.compile(optimizer="adam",
      loss="sparse_categorical_crossentropy",
      metrics=["accuracy"])
model.summary()

"""train the model"""

history=model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test),batch_size=64)



"""evaluate the model"""

test_loss,test_accuracy=model.evaluate(x_test,y_test)
print("test accuracy:",test_accuracy)

"""plot accuracy and loss"""

plt.figure(figsize=(14,5))
plt.subplot(1,2,2)
plt.plot(history.history['accuracy'],label="train accuracy")
plt.plot(history.history["val_accuracy"],label="validation accuracy")
plt.title("accuracy over epochs")
plt.xlabel("epochs")
plt.ylabel("accuracy")
plt.legend

plt.subplot(1,2,2)
plt.plot(history.history["loss"],label="train loss")
plt.plot(history.history["val_loss"],label="validation loss")
plt.title("loss over epochs")
plt.xlabel("epochs")
plt.ylabel("loss")
plt.legend()
plt.tight_layout()
plt.show()

"""prediction on test set"""

y_pred_prob=model.predict(x_test)
y_pred_classes=np.argmax(y_pred_prob,axis=1)

"""confusion matrix"""

cm=confusion_matrix(y_test,y_pred_classes)
plt.figure(figsize=(10,18))
sns.heatmap(cm,annot=True,fmt="d",cmap="Blues",xticklabels=class_names,yticklabels=class_names)
plt.xlabel("predicted labels")
plt.ylabel("true labels")
plt.title("confusion matrix")



print("\nClassification_report:")
print(classification_report(y_test,y_pred_classes,target_names=class_names))

"""predict and display result for a single test image"""

index=100# you can change this index to any valid index within the set
plt.figure(figsize=(3,3))
plt.imshow(x_test[index])
plt.title(f"Actual:{class_names[y_test[index]]}")
plt.xlabel(f"predicted:{class_names[y_pred_classes[index]]}")
plt.show()