# -*- coding: utf-8 -*-
"""CNN-VGG 16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JoTEdLBaaF7PeWRppJsisizJLt1lSsXr

**Import required libraries**
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import to_categorical

"""**Load and Sample Fashion MNIST dataset**"""

(x_train,y_train),(x_test,y_test)=tf.keras.datasets.fashion_mnist.load_data()

x_train,y_train=x_train[:100],y_train[:100]
x_test,y_test=x_test[:100],y_test[:100]

"""**Resize images to 224*224**"""

x_train=tf.image.resize(x_train,(224,224))
x_test=tf.image.resize(x_test,(224,224))

"""**Normalization**"""

x_train=x_train/255.0
x_test=x_test/255.0

"""**One hot encoding**"""

# Re-load the original data to ensure y_train and y_test are not None
(_, y_train_full), (_, y_test_full) = tf.keras.datasets.fashion_mnist.load_data()

# Sample to 100 as per previous steps in the notebook
y_train = y_train_full[:100]
y_test = y_test_full[:100]

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

"""**Load pretrained VGG16 without top layers**"""

base_model=VGG16(weights='imagenet',include_top=False,input_shape=(224,224,3))

"""**Freeze base model layers(Feature extraction)**"""

for layer in base_model.layers:
  layer.trainable=False

"""**Add custom top layers**"""

x=base_model.output
x=Flatten()(x)
x=Dense(256,activation="relu")(x)
x=Dropout(0.5)(x)
predictions=Dense(10,activation="softmax")(x)

"""**Create the final model**"""

model=Model(inputs=base_model.input,outputs=predictions)

"""**Compile the model(feature extraction Phase)**"""

model.compile(optimizer=Adam(learning_rate=1e-4),loss='categorical_crossentropy',metrics=['accuracy'])

"""**Train the model(only top layers)**"""

(raw_x_train, raw_y_train), (_, _) = tf.keras.datasets.fashion_mnist.load_data()
x_train_processed = raw_x_train[:100] # Slice to 100 samples
y_train_processed = raw_y_train[:100] # Slice to 100 samples


x_train_processed = tf.cast(x_train_processed, tf.float32) / 255.0


x_train_processed = tf.expand_dims(x_train_processed, axis=-1) # (100, 28, 28, 1)


x_train_processed = tf.image.resize(x_train_processed, (224, 224)) # (100, 224, 224, 1)


x_train_processed = tf.image.grayscale_to_rgb(x_train_processed) # (100, 224, 224, 3)


y_train_processed = to_categorical(y_train_processed)
y_train_processed = tf.cast(y_train_processed, tf.float32)

print(f"Shape of x_train_processed before model.fit: {x_train_processed.shape}")
print(f"Shape of y_train_processed before model.fit: {y_train_processed.shape}")


history=model.fit(x_train_processed.numpy(), y_train_processed.numpy(), epochs=5, batch_size=32, validation_split=0.2)

"""**Fine-tune some convolutional layer**"""

for layer in base_model.layers[-4:]:
  layer.trainable=True

"""**Compile Again(After unfreezing)**"""

model.compile(optimizer=Adam(learning_rate=1e-5),loss='categorical_crossentropy',metrics=['accuracy'])

# Re-load and process x_train and y_train for fine-tuning to ensure correct cardinality and shape
(raw_x_train, raw_y_train), (_, _) = tf.keras.datasets.fashion_mnist.load_data()
x_train_fine = raw_x_train[:100] # Slice to 100 samples
y_train_fine = raw_y_train[:100] # Slice to 100 samples

# Convert to float32 and normalize x_train
x_train_fine = tf.cast(x_train_fine, tf.float32) / 255.0

# Add channel dimension before resizing to correctly handle batch of grayscale images
x_train_fine = tf.expand_dims(x_train_fine, axis=-1) # (100, 28, 28, 1)

# Explicitly resize images to 224x224
x_train_fine = tf.image.resize(x_train_fine, (224, 224)) # (100, 224, 224, 1)

# Now convert to 3 channels for VGG16
x_train_fine = tf.image.grayscale_to_rgb(x_train_fine) # (100, 224, 224, 3)

# One-hot encode y_train and cast to float32
y_train_fine = to_categorical(y_train_fine)
y_train_fine = tf.cast(y_train_fine, tf.float32)

print(f"Shape of x_train_fine before model.fit: {x_train_fine.shape}")
print(f"Shape of y_train_fine before model.fit: {y_train_fine.shape}")

# Convert tensors to NumPy arrays to ensure concrete shapes for model.fit
history_fine=model.fit(x_train_fine.numpy(), y_train_fine.numpy(), epochs=5, batch_size=32,validation_split=0.2)

"""### Re-creating the model for evaluation context"""

# Load pretrained VGG16 without top layers
base_model=VGG16(weights='imagenet',include_top=False,input_shape=(224,224,3))

# Freeze base model layers(Feature extraction)
for layer in base_model.layers:
  layer.trainable=False

# Add custom top layers
x=base_model.output
x=Flatten()(x)
x=Dense(256,activation="relu")(x)
x=Dropout(0.5)(x)
predictions=Dense(10,activation="softmax")(x)

# Create the final model
model=Model(inputs=base_model.input,outputs=predictions)

# Compile the model(feature extraction Phase)
model.compile(optimizer=Adam(learning_rate=1e-4),loss='categorical_crossentropy',metrics=['accuracy'])

# Fine-tune some convolutional layer
for layer in base_model.layers[-4:]:
  layer.trainable=True

# Compile Again(After unfreezing)
model.compile(optimizer=Adam(learning_rate=1e-5),loss='categorical_crossentropy',metrics=['accuracy'])

"""**Evaluate on test set**"""

import tensorflow as tf
from tensorflow.keras.utils import to_categorical
# Re-load and process x_test and y_test to ensure correct cardinality and shape within this cell
(raw_x_test, raw_y_test), (_, _) = tf.keras.datasets.fashion_mnist.load_data()
x_test_processed = raw_x_test[:100] # Slice to 100 samples
y_test_processed = raw_y_test[:100] # Slice to 100 samples

# Convert to float32 and normalize x_test
x_test_processed = tf.cast(x_test_processed, tf.float32) / 255.0

# Add channel dimension before resizing to correctly handle batch of grayscale images
x_test_processed = tf.expand_dims(x_test_processed, axis=-1) # (100, 28, 28, 1)

# Explicitly resize images to 224x224
x_test_processed = tf.image.resize(x_test_processed, (224, 224)) # (100, 224, 224, 1)

# Now convert to 3 channels for VGG16
x_test_processed = tf.image.grayscale_to_rgb(x_test_processed) # (100, 224, 224, 3)

# One-hot encode y_test and cast to float32
y_test_processed = to_categorical(y_test_processed)
y_test_processed = tf.cast(y_test_processed, tf.float32)

print(f"Shape of x_test_processed before model.evaluate: {x_test_processed.shape}")
print(f"Shape of y_test_processed before model.evaluate: {y_test_processed.shape}")

# Convert tensors to NumPy arrays to ensure concrete shapes for model.evaluate
test_loss, test_acc = model.evaluate(x_test_processed.numpy(), y_test_processed.numpy())
print("Test Accuracy:", test_acc)
print("Test Loss:", test_loss)

"""**Plot accuracy graph**"""

plt.plot(history.history["accuracy"]+history_fine.history["accuracy"],label="Training accuracy")
plt.plot(history.history["val_accuracy"]+history_fine.history["val_accuracy"],label="Validation accuracy")
plt.legend()
plt.title("Training and validation accuracy")
plt.show()

