# -*- coding: utf-8 -*-
"""ML_ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6PKSfnhotoiYlcg3_361Lunyw6POQWy

TWO SUM
"""

def two_sum(nums, target):
    seen = {}

    for i, num in enumerate(nums):
        difference = target - num

        if difference in seen:
            return [seen[difference], i]

        seen[num] = i

    return []

nums = [2, 7, 11, 15]
target = 9

print(two_sum(nums, target))

"""VALID ANAGRAM"""

def is_anagram(s, t):
    return sorted(s) == sorted(t)

print(is_anagram("listen", "silent"))

"""Section 2: k-NN & Distance Logic

**1. K Closest Points to Origin**
"""

import math

def k_closest(points, k):
    points.sort(key=lambda p: math.sqrt(p[0]**2 + p[1]**2))
    return points[:k]

points = [[1, 3], [-2, 2], [5, 8]]
k = 2

print(k_closest(points, k))

"""**2. Find Nearest Point with Same X or Y**"""

def nearest_valid_point(x, y, points):
    min_distance = float('inf')
    index = -1

    for i, (px, py) in enumerate(points):
        if px == x or py == y:
            distance = abs(px - x) + abs(py - y)

            if distance < min_distance:
                min_distance = distance
                index = i

    return index

print(nearest_valid_point(3, 4, [(1,2), (3,1), (2,4), (3,4)]))

"""Section 3: Clustering & Grouping
**1. Group Anagrams**
"""

from collections import defaultdict

def group_anagrams(words):
    groups = defaultdict(list)

    for word in words:
        key = ''.join(sorted(word))
        groups[key].append(word)

    return list(groups.values())

words = ["eat", "tea", "tan", "ate", "nat", "bat"]

print(group_anagrams(words))

"""**2. Number of Islands**"""

def num_islands(grid):
    if not grid:
        return 0

    rows = len(grid)
    cols = len(grid[0])
    count = 0

    def dfs(r, c):
        if r < 0 or c < 0 or r >= rows or c >= cols or grid[r][c] == "0":
            return

        grid[r][c] = "0"

        dfs(r+1, c)
        dfs(r-1, c)
        dfs(r, c+1)
        dfs(r, c-1)

    for r in range(rows):
        for c in range(cols):
            if grid[r][c] == "1":
                count += 1
                dfs(r, c)

    return count

grid = [
    ["1","1","0","0"],
    ["1","0","0","1"],
    ["0","0","1","1"]
]

print(num_islands(grid))

"""Section 4: Matrix & Image Processing

**1. Flood Fill**
"""

def flood_fill(image, sr, sc, color):
    original = image[sr][sc]

    if original == color:
        return image

    def dfs(r, c):
        if r < 0 or c < 0 or r >= len(image) or c >= len(image[0]):
            return

        if image[r][c] != original:
            return

        image[r][c] = color

        dfs(r+1, c)
        dfs(r-1, c)
        dfs(r, c+1)
        dfs(r, c-1)

    dfs(sr, sc)

    return image

image = [
    [1,1,1],
    [1,1,0],
    [1,0,1]
]

print(flood_fill(image, 1, 1, 2))

"""**Set matrix zeroes**"""

def set_zeroes(matrix):
    rows = set()
    cols = set()

    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] == 0:
                rows.add(i)
                cols.add(j)

    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if i in rows or j in cols:
                matrix[i][j] = 0

    return matrix

matrix = [
    [1,1,1],
    [1,0,1],
    [1,1,1]
]

print(set_zeroes(matrix))

"""Section 5: Sliding Window
1. Maximum Average Subarray
"""

def find_max_average(nums, k):
    window_sum = sum(nums[:k])
    max_sum = window_sum

    for i in range(k, len(nums)):
        window_sum += nums[i] - nums[i-k]
        max_sum = max(max_sum, window_sum)

    return max_sum / k

nums = [1,12,-5,-6,50,3]
k = 4

print(find_max_average(nums, k))

"""2. Sliding Window Maximum"""

from collections import deque

def max_sliding_window(nums, k):
    dq = deque()
    result = []

    for i in range(len(nums)):
        while dq and dq[0] <= i-k:
            dq.popleft()

        while dq and nums[dq[-1]] < nums[i]:
            dq.pop()

        dq.append(i)

        if i >= k-1:
            result.append(nums[dq[0]])

    return result

print(max_sliding_window([1,3,-1,-3,5,3,6,7], 3))

"""Section 6: HackerRank Practice
1. Lists
"""

lst = []

lst.append(1)
lst.append(2)
lst.insert(1, 5)

print(lst)

lst.remove(5)

print(lst)

"""**Nested lists**"""

students = [
    ["Harry", 37.21],
    ["Berry", 37.21],
    ["Tina", 37.2],
    ["Akriti", 41],
    ["Harsh", 39]
]

scores = sorted(set(score for name, score in students))

second_lowest = scores[1]

names = sorted(name for name, score in students if score == second_lowest)

for name in names:
    print(name)

"""3. Runner-Up Score"""

scores = [2, 3, 6, 6, 5]

unique_scores = list(set(scores))
unique_scores.sort()

print(unique_scores[-2])

"""Mini Project: Build Your Own k-NN"""

import math

dataset = [
    (150, 7, 'apple'),
    (130, 6, 'orange')
]

new_point = (140, 6.5)

def euclidean_distance(p1, p2):
    return math.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)

nearest_label = None
min_distance = float('inf')

for fruit in dataset:
    distance = euclidean_distance(new_point, fruit[:2])

    print(f"Distance from {fruit[2]} = {distance}")

    if distance < min_distance:
        min_distance = distance
        nearest_label = fruit[2]

print("Predicted Label:", nearest_label)